spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean" # To make Shell work
  change-logs-scan-package:
    - homework8.mongock.changelogs

  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR